export const LEASE_STAGE = {
  BASIC_DETAILS:              'BASIC_DETAILS',
  COMMERCIAL_DETAILS:         'COMMERCIAL_DETAILS',
  MANAGER_APPROVAL_REQUIRED:  'MANAGER_APPROVAL_REQUIRED',
  MANAGER_APPROVED:           'MANAGER_APPROVED',
  INVITE:                     'INVITE',
  WAITING_FOR_SIGNUP:         'WAITING_FOR_SIGNUP',
  ONBOARDING:                 'ONBOARDING',
  NEGOTIATION_SENT:           'NEGOTIATION_SENT',
  PENDING_APPROVAL:           'PENDING_APPROVAL',
  OWNER_APPROVED:             'OWNER_APPROVED',
  TENANT_APPROVED:            'TENANT_APPROVED',
  WAITING_CHEQUE:             'WAITING_CHEQUE',
  CHEQUE_REQUESTED:           'CHEQUE_REQUESTED',
  CHEQUE_COLLECTED:           'CHEQUE_COLLECTED',
  AGREEMENT:                  'AGREEMENT',
  AGREEMENT_SIGNING:          'AGREEMENT_SIGNING',
  AGREEMENT_SIGNED:           'AGREEMENT_SIGNED',
  EJARI:                      'EJARI',
  EJARI_SIGNING:              'EJARI_SIGNING',
  ACTIVATED:                  'ACTIVATED',
} as const;

export type LeaseStage = typeof LEASE_STAGE[keyof typeof LEASE_STAGE];
