import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { SortingIconComponent } from '../icons/sorting-icon/sorting-icon.component';

@Component({
  selector: 'app-email-leads',
  standalone: true,
  imports: [CommonModule, SortingIconComponent],
  templateUrl: './email-leads.component.html',
  styleUrl: './email-leads.component.css',
})
export class EmailLeadsComponent {
  leads = [
    {
      name: 'Rakesh Jadhav',
      status: 'Interested',
      statusClass: 'green',
      intent: 'Meeting intent',
      company: 'Anulom Technologies Pvt <> Doqfy | E-Stamping',
      owner: 'Vinayak | 1000 Acc',
      date: 'Sep 9',
      isEmail: true,
    },
    {
      name: 'Dhanasekar Prashanth',
      status: 'Interested',
      statusClass: 'green',
      company: 'Connection Request ',
      message: ' The only ask currently I have is for a Demo with ...',
      owner: 'LinkedIn - Amin',
      date: 'Sep 6',
      isEmail: false,
    },
    {
      name: 'Kshitij Shah',
      status: 'Interested',
      statusClass: 'green',
      company: 'RATNAAFIN <> Doqfy | E-Stamping | E-Signature | Contract ...',
      owner: 'Vinayak | 1000 Acc',
      date: 'Sep 5',
      isEmail: true,
    },
    {
      name: 'Mahendra Kumawat',
      status: 'Not interested',
      statusClass: 'gray',
      company: 'LinkedIn Message ',
      message: ' No, thanks',
      owner: 'Vineet 15 July',
      date: 'Aug 30',
      isEmail: false,
    },
    {
      name: 'Harshal Patil',
      status: '',
      statusClass: '',
      company: 'Connection Request ',
      message: ' Avalog.com',
      owner: 'Vineet 15 July',
      date: 'Aug 29',
      isEmail: false,
    },
    {
      name: 'Dhiren Panchal',
      status: '',
      statusClass: '',
      company: 'Connection Request ',
      message: ' Thanks for letting me know',
      owner: 'LinkedIn - Vinayak',
      date: 'Aug 29',
      isEmail: false,
    },
    {
      name: 'Hemangi Jadhav',
      status: '',
      statusClass: '',
      company: 'LinkedIn Message ',
      message: ' No, thank you',
      owner: 'Vineet 15 July',
      date: 'Aug 29',
      isEmail: false,
    },
    {
      name: 'Karthick G',
      status: 'Do not contact',
      statusClass: 'orange',
      company: 'Vayavya Labs Pvt <> Doqfy | E-Stamping | E-Signature ...',
      owner: 'Vinayak | 1000 Acc',
      date: 'Aug 28',
      isEmail: true,
    },
    {
      name: 'Amarsinh Parmar',
      status: '',
      statusClass: '',
      company: 'Connection Request ',
      message: ' Hi, Actually all contract are initiated by our clients only.',
      owner: 'Vineet 15 July',
      date: 'Aug 28',
      isEmail: false,
    },
    {
      name: 'Vidhu J',
      status: '',
      statusClass: '',
      company: 'LinkedIn Message ',
      message:
        ' Not at the moment, i will come back when there is a requirement',
      owner: 'Vineet 15 July',
      date: 'Aug 26',
      isEmail: false,
    },
    {
      name: 'Ashish Mohan Jha',
      status: '',
      statusClass: '',
      company: 'Connection Request ',
      message: ' Thanks for letting me know',
      owner: 'Vineet 15 July',
      date: 'Aug 25',
      isEmail: false,
    },
  ];
}
